from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime

class PharmacyProduct(BaseModel):
    id: str
    name: str
    description: str
    category: str
    price: float
    imageUrl: str
    rating: float
    reviewCount: int
    isPrescription: bool
    tags: List[str]
    stock: int
    manufacturer: str
    dosage: str
    expiryDate: datetime
    isFeatured: bool

    class Config:
        json_schema_extra = {
            "example": {
                "id": "prod_001",
                "name": "Paracetamol 500mg",
                "description": "Obat pereda nyeri dan demam",
                "category": "Analgesik & Antiinflamasi",
                "price": 15000.0,
                "imageUrl": "https://via.placeholder.com/300x200",
                "rating": 4.5,
                "reviewCount": 120,
                "isPrescription": False,
                "tags": ["Pereda Nyeri", "Anti Demam"],
                "stock": 50,
                "manufacturer": "Kalbe Farma",
                "dosage": "1 tablet setiap 4-6 jam",
                "expiryDate": "2025-12-31T00:00:00",
                "isFeatured": True
            }
        }


# DATA DUMMY LENGKAP (35 produk)
PHARMACY_PRODUCTS_DATA = [
    {
        "id": "prod_001",
        "name": "Paracetamol 500mg",
        "description": "Obat pereda nyeri dan demam yang aman untuk segala usia",
        "category": "Analgesik & Antiinflamasi",
        "price": 15000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.5,
        "reviewCount": 120,
        "isPrescription": False,
        "tags": ["Pereda Nyeri", "Anti Demam", "OTC"],
        "stock": 50,
        "manufacturer": "Kalbe Farma",
        "dosage": "1 tablet setiap 4-6 jam",
        "expiryDate": "2025-12-31T00:00:00",
        "isFeatured": True
    },
    {
        "id": "prod_002",
        "name": "Ibuprofen 400mg",
        "description": "Antiinflamasi non-steroid untuk nyeri dan radang",
        "category": "Analgesik & Antiinflamasi",
        "price": 25000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w-400",
        "rating": 4.3,
        "reviewCount": 89,
        "isPrescription": True,
        "tags": ["Anti Radang", "Nyeri Otot"],
        "stock": 30,
        "manufacturer": "Kimia Farma",
        "dosage": "1-2 tablet setiap 8 jam",
        "expiryDate": "2025-06-30T00:00:00",
        "isFeatured": False
    },
    {
        "id": "prod_003",
        "name": "Amoxicillin 500mg",
        "description": "Antibiotik spektrum luas untuk infeksi bakteri",
        "category": "Antibiotik",
        "price": 35000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.6,
        "reviewCount": 156,
        "isPrescription": True,
        "tags": ["Antibiotik", "Infeksi"],
        "stock": 25,
        "manufacturer": "Sanbe Farma",
        "dosage": "1 kapsul setiap 8 jam",
        "expiryDate": "2024-12-15T00:00:00",
        "isFeatured": True
    },
    {
        "id": "prod_004",
        "name": "Vitamin C 1000mg",
        "description": "Suplemen daya tahan tubuh dengan antioksidan tinggi",
        "category": "Vitamin & Suplemen",
        "price": 45000.0,
        "imageUrl": "https://images.unsplash.com/photo-1550259979-02152cd8e7e0?w=400",
        "rating": 4.8,
        "reviewCount": 234,
        "isPrescription": False,
        "tags": ["Imunitas", "Antioksidan"],
        "stock": 100,
        "manufacturer": "Sido Muncul",
        "dosage": "1 tablet per hari",
        "expiryDate": "2026-03-31T00:00:00",
        "isFeatured": True
    },
    {
        "id": "prod_005",
        "name": "Metformin 500mg",
        "description": "Obat untuk mengontrol kadar gula darah pada diabetes tipe 2",
        "category": "Obat Diabetes",
        "price": 28000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.4,
        "reviewCount": 67,
        "isPrescription": True,
        "tags": ["Diabetes", "Gula Darah"],
        "stock": 40,
        "manufacturer": "Dexa Medica",
        "dosage": "1-2 tablet per hari",
        "expiryDate": "2025-09-30T00:00:00",
        "isFeatured": False
    },
    {
        "id": "prod_006",
        "name": "Cetirizine 10mg",
        "description": "Antihistamin untuk alergi dan gatal-gatal",
        "category": "Obat Alergi",
        "price": 18000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.2,
        "reviewCount": 98,
        "isPrescription": False,
        "tags": ["Anti Alergi", "Gatal"],
        "stock": 60,
        "manufacturer": "Kalbe Farma",
        "dosage": "1 tablet per hari",
        "expiryDate": "2025-11-30T00:00:00",
        "isFeatured": False
    },
    {
        "id": "prod_007",
        "name": "Omeprazole 20mg",
        "description": "Penghambat pompa proton untuk maag dan asam lambung",
        "category": "Obat Lambung",
        "price": 32000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.5,
        "reviewCount": 112,
        "isPrescription": True,
        "tags": ["Maag", "Asam Lambung"],
        "stock": 35,
        "manufacturer": "Pharos",
        "dosage": "1 kapsul sebelum makan",
        "expiryDate": "2025-08-31T00:00:00",
        "isFeatured": True
    },
    {
        "id": "prod_008",
        "name": "Salbutamol Inhaler",
        "description": "Bronkodilator untuk asma dan sesak nafas",
        "category": "Obat Pernafasan",
        "price": 65000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.7,
        "reviewCount": 87,
        "isPrescription": True,
        "tags": ["Asma", "Sesak Nafas"],
        "stock": 20,
        "manufacturer": "GlaxoSmithKline",
        "dosage": "2-4 hirupan setiap 4-6 jam",
        "expiryDate": "2025-05-31T00:00:00",
        "isFeatured": True
    },
    {
        "id": "prod_009",
        "name": "Vitamin D3 1000 IU",
        "description": "Suplemen untuk kesehatan tulang dan imunitas",
        "category": "Vitamin & Suplemen",
        "price": 55000.0,
        "imageUrl": "https://images.unsplash.com/photo-1550259979-02152cd8e7e0?w=400",
        "rating": 4.6,
        "reviewCount": 145,
        "isPrescription": False,
        "tags": ["Tulang", "Imunitas"],
        "stock": 80,
        "manufacturer": "Nature's Plus",
        "dosage": "1 softgel per hari",
        "expiryDate": "2026-01-31T00:00:00",
        "isFeatured": False
    },
    {
        "id": "prod_010",
        "name": "Atorvastatin 20mg",
        "description": "Statin untuk menurunkan kolesterol LDL",
        "category": "Obat Jantung",
        "price": 42000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.4,
        "reviewCount": 76,
        "isPrescription": True,
        "tags": ["Kolesterol", "Jantung"],
        "stock": 45,
        "manufacturer": "Pfizer",
        "dosage": "1 tablet malam hari",
        "expiryDate": "2025-10-31T00:00:00",
        "isFeatured": False
    },
    {
        "id": "prod_011",
        "name": "Tolak Angin Cair",
        "description": "Obat herbal untuk masuk angin dan flu",
        "category": "Herbal",
        "price": 12000.0,
        "imageUrl": "https://images.unsplash.com/photo-1599045118103-54ddc1d4a695?w=400",
        "rating": 4.3,
        "reviewCount": 210,
        "isPrescription": False,
        "tags": ["Flu", "Masuk Angin", "Herbal"],
        "stock": 150,
        "manufacturer": "Sido Muncul",
        "dosage": "1 sachet 2-3 kali sehari",
        "expiryDate": "2026-06-30T00:00:00",
        "isFeatured": True
    },
    {
        "id": "prod_012",
        "name": "Bodrex Extra",
        "description": "Pereda sakit kepala dan demam",
        "category": "Analgesik & Antiinflamasi",
        "price": 8000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.1,
        "reviewCount": 189,
        "isPrescription": False,
        "tags": ["Sakit Kepala", "Demam"],
        "stock": 200,
        "manufacturer": "Bayer",
        "dosage": "1-2 tablet setiap 4-6 jam",
        "expiryDate": "2026-02-28T00:00:00",
        "isFeatured": False
    },
    {
        "id": "prod_013",
        "name": "Betadine Solution",
        "description": "Antiseptik untuk luka dan kulit",
        "category": "Obat Kulit",
        "price": 22000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.5,
        "reviewCount": 134,
        "isPrescription": False,
        "tags": ["Antiseptik", "Luka"],
        "stock": 75,
        "manufacturer": "Mundipharma",
        "dosage": "Oleskan pada luka 2-3 kali sehari",
        "expiryDate": "2025-07-31T00:00:00",
        "isFeatured": False
    },
    {
        "id": "prod_014",
        "name": "Insto Regular",
        "description": "Tetes mata untuk mata merah dan iritasi",
        "category": "Obat Mata",
        "price": 28000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.4,
        "reviewCount": 98,
        "isPrescription": False,
        "tags": ["Mata Merah", "Iritasi"],
        "stock": 55,
        "manufacturer": "Meprofarm",
        "dosage": "1-2 tetes 3-4 kali sehari",
        "expiryDate": "2025-04-30T00:00:00",
        "isFeatured": False
    },
    {
        "id": "prod_015",
        "name": "Diapet",
        "description": "Obat anti diare dengan cepat",
        "category": "Obat Lambung",
        "price": 15000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.2,
        "reviewCount": 167,
        "isPrescription": False,
        "tags": ["Diare", "Sakit Perut"],
        "stock": 90,
        "manufacturer": "Darya-Varia",
        "dosage": "2 kapsul awal, lalu 1 kapsul setiap BAB",
        "expiryDate": "2025-12-31T00:00:00",
        "isFeatured": False
    },
    {
        "id": "prod_016",
        "name": "Antimo 50mg",
        "description": "Obat untuk mabuk perjalanan dan mual",
        "category": "Obat Lambung",
        "price": 10000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.3,
        "reviewCount": 143,
        "isPrescription": False,
        "tags": ["Mabuk Perjalanan", "Mual"],
        "stock": 120,
        "manufacturer": "Combiphar",
        "dosage": "1 tablet 30 menit sebelum perjalanan",
        "expiryDate": "2026-03-31T00:00:00",
        "isFeatured": False
    },
    {
        "id": "prod_017",
        "name": "Laserin Cream",
        "description": "Krim antijamur untuk panu dan kurap",
        "category": "Obat Kulit",
        "price": 32000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.4,
        "reviewCount": 89,
        "isPrescription": True,
        "tags": ["Antijamur", "Panu", "Kurap"],
        "stock": 40,
        "manufacturer": "Interbat",
        "dosage": "Oles tipis 2 kali sehari",
        "expiryDate": "2025-08-15T00:00:00",
        "isFeatured": False
    },
    {
        "id": "prod_018",
        "name": "Sangobion",
        "description": "Suplemen penambah darah untuk anemia",
        "category": "Vitamin & Suplemen",
        "price": 38000.0,
        "imageUrl": "https://images.unsplash.com/photo-1550259979-02152cd8e7e0?w=400",
        "rating": 4.7,
        "reviewCount": 178,
        "isPrescription": False,
        "tags": ["Anemia", "Penambah Darah"],
        "stock": 65,
        "manufacturer": "Merek",
        "dosage": "1 kapsul per hari",
        "expiryDate": "2025-11-30T00:00:00",
        "isFeatured": True
    },
    {
        "id": "prod_019",
        "name": "Termometer Digital",
        "description": "Termometer digital akurat dengan hasil cepat",
        "category": "Alat Kesehatan",
        "price": 85000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.6,
        "reviewCount": 234,
        "isPrescription": False,
        "tags": ["Termometer", "Digital"],
        "stock": 30,
        "manufacturer": "Omron",
        "dosage": "Penggunaan sesuai manual",
        "expiryDate": "2027-12-31T00:00:00",
        "isFeatured": True
    },
    {
        "id": "prod_020",
        "name": "Masker Bedah 3 Ply",
        "description": "Masker medis untuk perlindungan sehari-hari",
        "category": "Alat Kesehatan",
        "price": 25000.0,
        "imageUrl": "https://images.unsplash.com/photo-1584634731339-252c581abfc5?w=400",
        "rating": 4.5,
        "reviewCount": 567,
        "isPrescription": False,
        "tags": ["Masker", "Proteksi"],
        "stock": 500,
        "manufacturer": "Medicom",
        "dosage": "Pakai maksimal 4 jam",
        "expiryDate": "2026-08-31T00:00:00",
        "isFeatured": False
    },
    {
        "id": "prod_021",
        "name": "Tensimeter Digital",
        "description": "Alat ukur tekanan darah otomatis",
        "category": "Alat Kesehatan",
        "price": 325000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.8,
        "reviewCount": 89,
        "isPrescription": False,
        "tags": ["Tensi", "Tekanan Darah"],
        "stock": 15,
        "manufacturer": "Omron",
        "dosage": "Penggunaan sesuai manual",
        "expiryDate": "2028-06-30T00:00:00",
        "isFeatured": True
    },
    {
        "id": "prod_022",
        "name": "Madu TJ Murni",
        "description": "Madu murni untuk daya tahan tubuh",
        "category": "Herbal",
        "price": 65000.0,
        "imageUrl": "https://images.unsplash.com/photo-1599045118103-54ddc1d4a695?w=400",
        "rating": 4.9,
        "reviewCount": 456,
        "isPrescription": False,
        "tags": ["Madu", "Herbal", "Imunitas"],
        "stock": 80,
        "manufacturer": "Mustika Ratu",
        "dosage": "1-2 sendok makan per hari",
        "expiryDate": "2026-05-31T00:00:00",
        "isFeatured": True
    },
    {
        "id": "prod_023",
        "name": "Kaplet Spirulina",
        "description": "Suplemen alga kaya nutrisi",
        "category": "Vitamin & Suplemen",
        "price": 75000.0,
        "imageUrl": "https://images.unsplash.com/photo-1550259979-02152cd8e7e0?w=400",
        "rating": 4.5,
        "reviewCount": 123,
        "isPrescription": False,
        "tags": ["Spirulina", "Detoks"],
        "stock": 45,
        "manufacturer": "CNI",
        "dosage": "2 kaplet 2 kali sehari",
        "expiryDate": "2025-10-31T00:00:00",
        "isFeatured": False
    },
    {
        "id": "prod_024",
        "name": "Obat Batuk Hitam",
        "description": "Obat batuk berdahak tradisional",
        "category": "Obat Pernafasan",
        "price": 12000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.2,
        "reviewCount": 189,
        "isPrescription": False,
        "tags": ["Batuk", "Dahak"],
        "stock": 110,
        "manufacturer": "Konimex",
        "dosage": "1 sendok takar 3 kali sehari",
        "expiryDate": "2025-09-30T00:00:00",
        "isFeatured": False
    },
    {
        "id": "prod_025",
        "name": "Vicks Inhaler",
        "description": "Inhaler untuk hidung tersumbat",
        "category": "Obat Pernafasan",
        "price": 28000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.6,
        "reviewCount": 267,
        "isPrescription": False,
        "tags": ["Hidung Tersumbat", "Pilek"],
        "stock": 70,
        "manufacturer": "Procter & Gamble",
        "dosage": "Hirup sesuai kebutuhan",
        "expiryDate": "2025-12-31T00:00:00",
        "isFeatured": True
    },
    {
        "id": "prod_026",
        "name": "Salep 88",
        "description": "Salep untuk gatal dan kulit kering",
        "category": "Obat Kulit",
        "price": 18000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.3,
        "reviewCount": 145,
        "isPrescription": False,
        "tags": ["Gatal", "Kulit Kering"],
        "stock": 95,
        "manufacturer": "Sido Muncul",
        "dosage": "Oles tipis 2-3 kali sehari",
        "expiryDate": "2025-06-30T00:00:00",
        "isFeatured": False
    },
    {
        "id": "prod_027",
        "name": "Promag Tablet",
        "description": "Antasida untuk sakit maag akut",
        "category": "Obat Lambung",
        "price": 22000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.7,
        "reviewCount": 298,
        "isPrescription": False,
        "tags": ["Maag", "Asam Lambung"],
        "stock": 120,
        "manufacturer": "Kalbe Farma",
        "dosage": "1-2 tablet saat gejala",
        "expiryDate": "2026-01-31T00:00:00",
        "isFeatured": False
    },
    {
        "id": "prod_028",
        "name": "Tremenza",
        "description": "Obat untuk vertigo dan pusing berputar",
        "category": "Neurologi",
        "price": 42000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.4,
        "reviewCount": 67,
        "isPrescription": True,
        "tags": ["Vertigo", "Pusing"],
        "stock": 25,
        "manufacturer": "Sanbe Farma",
        "dosage": "1 tablet 3 kali sehari",
        "expiryDate": "2025-07-31T00:00:00",
        "isFeatured": False
    },
    {
        "id": "prod_029",
        "name": "Cataflam 50mg",
        "description": "Antiinflamasi untuk nyeri akut",
        "category": "Analgesik & Antiinflamasi",
        "price": 32000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.5,
        "reviewCount": 98,
        "isPrescription": True,
        "tags": ["Nyeri Akut", "Radang"],
        "stock": 35,
        "manufacturer": "Novartis",
        "dosage": "1 tablet setiap 8 jam",
        "expiryDate": "2025-05-31T00:00:00",
        "isFeatured": False
    },
    {
        "id": "prod_030",
        "name": "Vitamin B Complex",
        "description": "Suplemen untuk metabolisme energi",
        "category": "Vitamin & Suplemen",
        "price": 38000.0,
        "imageUrl": "https://images.unsplash.com/photo-1550259979-02152cd8e7e0?w=400",
        "rating": 4.6,
        "reviewCount": 167,
        "isPrescription": False,
        "tags": ["Energi", "Metabolisme"],
        "stock": 60,
        "manufacturer": "Blackmores",
        "dosage": "1 tablet per hari",
        "expiryDate": "2025-11-30T00:00:00",
        "isFeatured": True
    },
    {
        "id": "prod_031",
        "name": "Minyak Kayu Putih",
        "description": "Minyak angin untuk pegal dan masuk angin",
        "category": "Herbal",
        "price": 15000.0,
        "imageUrl": "https://images.unsplash.com/photo-1599045118103-54ddc1d4a695?w=400",
        "rating": 4.8,
        "reviewCount": 345,
        "isPrescription": False,
        "tags": ["Pegal", "Angin"],
        "stock": 200,
        "manufacturer": "Cap Lang",
        "dosage": "Oles tipis pada area nyeri",
        "expiryDate": "2026-09-30T00:00:00",
        "isFeatured": False
    },
    {
        "id": "prod_032",
        "name": "Mylanta Sirup",
        "description": "Antasida cair untuk gangguan lambung",
        "category": "Obat Lambung",
        "price": 32000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.5,
        "reviewCount": 134,
        "isPrescription": False,
        "tags": ["Maag", "Antasida"],
        "stock": 55,
        "manufacturer": "Johnson & Johnson",
        "dosage": "2 sendok teh setiap 4 jam",
        "expiryDate": "2025-08-31T00:00:00",
        "isFeatured": False
    },
    {
        "id": "prod_033",
        "name": "Panadol Extra",
        "description": "Pereda nyeri dengan kafein",
        "category": "Analgesik & Antiinflamasi",
        "price": 22000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.4,
        "reviewCount": 189,
        "isPrescription": False,
        "tags": ["Nyeri", "Kafein"],
        "stock": 85,
        "manufacturer": "GSK",
        "dosage": "1-2 tablet setiap 4-6 jam",
        "expiryDate": "2025-10-31T00:00:00",
        "isFeatured": False
    },
    {
        "id": "prod_034",
        "name": "Obat Kumur Betadine",
        "description": "Antiseptik untuk mulut dan tenggorokan",
        "category": "Obat Mulut & Tenggorokan",
        "price": 45000.0,
        "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
        "rating": 4.6,
        "reviewCount": 112,
        "isPrescription": False,
        "tags": ["Sariawan", "Tenggorokan"],
        "stock": 40,
        "manufacturer": "Mundipharma",
        "dosage": "Berkumur 15 ml selama 30 detik",
        "expiryDate": "2025-07-31T00:00:00",
        "isFeatured": False
    },
    {
        "id": "prod_035",
        "name": "Nature's Health Omega-3",
        "description": "Suplemen minyak ikan untuk jantung",
        "category": "Vitamin & Suplemen",
        "price": 95000.0,
        "imageUrl": "https://images.unsplash.com/photo-1550259979-02152cd8e7e0?w=400",
        "rating": 4.7,
        "reviewCount": 89,
        "isPrescription": False,
        "tags": ["Omega-3", "Jantung"],
        "stock": 30,
        "manufacturer": "Nature's Way",
        "dosage": "1 softgel 2 kali sehari",
        "expiryDate": "2025-12-31T00:00:00",
        "isFeatured": True
    }
]